### ISSUE TITLE
Add Enhance to JavaScript Site Generator Review

### ISSUE THREAD

**Issue by zachleat** [zachleat/zachleat.com#44]
https://www.zachleat.com/web/site-generator-review/

https://enhance.dev/docs/

via https://indieweb.social/@brianleroux/109922551996532020

cc @brianleroux

**Comment by kristoferjoseph** [comment]
Exactly what @brianleroux said.
The repos are versioned with semver to show major minor patch for the individual packages.
The [Starter project](https://github.com/enhance-dev/enhance-starter-project/) is where you can use the latest and greatest of **all Enhance** but the project itself has not hit 1.0 yet because we are still incorporating user feedback from our initial beta release.

**Comment by zachleat** [comment]
Ah @kristoferjoseph so what should I list as the current version of Enhance? It doesn’t seem like 3.0.9 is right for that

**Comment by brianleroux** [comment]
lets go with `1.4.6` which is the docs site https://github.com/enhance-dev/enhance.dev/tags

**Comment by zachleat** [comment]
Shipping!

I did notice y’all removed the Eleventy plugin from your web site! 😭
